--1
SELECT DEPT_NO, COUNT(*) AS "EMPLE POR DEPART"
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT(*)>4
ORDER BY COUNT(*) DESC;

--2
SELECT DEPT_NO, SUM(SALARIO) AS "SUMA DE SALARIOS",MAX(SALARIO) AS "SALARIO MAX", MIN(SALARIO) AS "SALARIO MIN"
FROM EMPLE
GROUP BY DEPT_NO
ORDER BY DEPT_NO ASC;