--AVERIGUAR LAS COLUMNAS DE LA TABLA DEPARTSEQ
DESC DEPARTSEQ;

INSERT INTO DEPARTSEQ (DEPT_NO, DNOMBRE) VALUES 
(DEPT_ID_SEQ, NEXTVAL, 'EDUCACION');
INSERT INTO DEPARTSEQ (DEPT_NO, DNOMBRE) VALUES 
(DEPT_ID_SEQ, NEXTVAL, 'ADMINISTRACION');

--TAMAÑO DE DEPT_NO HAY QUE AUMNETAR PARA PODER HACER LAS INSERT
ALTER TABLE DEPARTSEQ MODIFY DEPT_NO NUMBER(4);

--COMPROBAR EL EL ALTER
DESC DEPARTSEQ;
COMMIT;

--LANZAR OTRA VEZ LOS INSERT
INSERT INTO DEPARTSEQ (DEPT_NO, DNOMBRE) VALUES 
(DEPT_ID_SEQ.CURRVAL, 'EDUCACION');
INSERT INTO DEPARTSEQ (DEPT_NO, DNOMBRE) VALUES 
(DEPT_ID_SEQ.NEXTVAL, 'ADMINISTRACION');

--COMPROBAR LAS INSERT
SELECT *FROM DEPARTSEQ;