DROP TABLE ALUMNOS;

CREATE TABLE ALUMNOS(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(30) NOT NULL,
EDAD NUMBER(2),
CURSO NUMBER(1),
CONSTRAINT ALU_DNI_PK PRIMARY KEY(DNI),
CONSTRAINT ALU_EDA_CK CHECK(EDAD BETWEEN 5 AND 20),
CONSTRAINT ALU_NOM_CK CHECK(NOMBRE=UPPER(NOMBRE)),
CONSTRAINT ALU_CUR_CK CHECK(CURSO IN(1,2,3))
);

--COMENTARIO
/*
COMENTARIO DE BLOQUE
*/

ALTER TABLE ALUMNOS ADD(
    SEXO VARCHAR2(1) NOT NULL CONSTRAINT ALU_SEX_CK CHECK(SEXO IN ('M','F')),
    IMPORTE NUMBER(10,2) DEFAULT 0
);

ALTER TABLE ALUMNOS DROP(
    EDAD
);
ALTER TABLE ALUMNOS ADD(
    FECHA_ALTA DATE,
    FECHA_NAC DATE,
    CONSTRAINT ALU_FEC_CK CHECK(FECHA_NAC<FECHA_ALTA)
    
);

ALTER TABLE ALUMNOS DROP CONSTRAINT ALU_FEC_CK;
ALTER TABLE ALUMNOS DROP(
FECHA_NAC
);

ALTER TABLE ALUMNOS 
RENAME COLUMN IMPORTE TO TASAS;

/*
DESC ALUMNOS;

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME='ALUMNOS';
*/

/*---------------------------------------------------------------*/

DROP TABLE PERSONAS;
DROP TABLE PROVINCIAS CASCADE CONSTRAINTS;
--CONSTRAINT EN MODO COLUMNA
/*
CREATE TABLE PROVINCIAS(
    COD_PROV NUMBER(2) CONSTRAINT PROV_COD_PK PRIMARY KEY,
    NOM_PROV VARCHAR2(15),
);
*/

--CONSTRAINT EN MODO TABLA
CREATE TABLE PROVINCIAS(
    COD_PROV NUMBER(2),
    NOM_PROV VARCHAR2(15),
    CONSTRAINT PROV_COD_PK PRIMARY KEY(COD_PROV)
);


CREATE TABLE PERSONAS(
    DNI NUMBER(8),
    NOMBRE VARCHAR2(15),
    DIRECCION VARCHAR2(25),
    POBLACION VARCHAR2(20),
    COD_PROV NUMBER(2) ,
    CONSTRAINT PER_DNI_PK PRIMARY KEY(DNI),
    CONSTRAINT PER_COD_PROV_FK FOREIGN KEY(COD_PROV)  
        REFERENCES PROVINCIAS(COD_PROV)
    );

RENAME PERSONAS TO CIUDADANOS;
DROP TABLE CIUDADANOS;

/*
DESC USER_TABLES;

SELECT TABLE_NAME FROM USER_TABLES
WHERE TABLE_NAME IN ('CIUDADANOS', 'PROVINCIAS','PERSONAS');

DESC CIUDADANOS;
DESC USER_CONSTRAINTS;

SELECT TABLE_NAME, SEARCH_CONDITION, CONSTRAINT_NAME,CONSTRAINT_TYPE FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('CIUDADANOS', 'PROVINCIAS');
*/



