DROP TABLE ALUMNOS;

CREATE TABLE ALUMNOS(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(30) NOT NULL,
EDAD NUMBER(2),
CURSO NUMBER(1),
CONSTRAINT ALU_DNI_PK PRIMARY KEY(DNI),
CONSTRAINT ALU_EDA_CK CHECK(EDAD BETWEEN 5 AND 20),
CONSTRAINT ALU_NOM_CK CHECK(NOMBRE=UPPER(NOMBRE)),
CONSTRAINT ALU_CUR_CK CHECK(CURSO IN(1,2,3))
);

--COMENTARIO
/*
COMENTARIO DE BLOQUE
*/

ALTER TABLE ALUMNOS ADD(
    SEXO VARCHAR2(1) NOT NULL CONSTRAINT ALU_SEX_CK CHECK(SEXO IN ('M','F')),
    IMPORTE NUMBER(10,2) DEFAULT 0
);

ALTER TABLE ALUMNOS DROP(
    EDAD
);
ALTER TABLE ALUMNOS ADD(
    FECHA_ALTA DATE,
    FECHA_NAC DATE,
    CONSTRAINT ALU_FEC_CK CHECK(FECHA_NAC<FECHA_ALTA)
    
);

ALTER TABLE ALUMNOS DROP CONSTRAINT ALU_FEC_CK;
ALTER TABLE ALUMNOS DROP(
FECHA_NAC
);

ALTER TABLE ALUMNOS 
RENAME COLUMN IMPORTE TO TASAS;

/*
DESC ALUMNOS;

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME='ALUMNOS';
*/
