--1 
/*Crea una tabla que sea igual que la tabla DEPART denominada DEPARTSEQ*/
DROP TABLE DEPARTSEQ;
CREATE TABLE DEPARTSEQ AS (
SELECT * FROM DEPART
);

DESC DEPART;
SELECT C.CONSTRAINT_NAME, C.CONSTRAINT_TYPE, CC.COLUMN_NAME 
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE UPPER(C.TABLE_NAME)='DEPART'
AND
C.CONSTRAINT_NAME=CC.CONSTRAINT_NAME;

DESC DEPARTSEQ;
SELECT C.CONSTRAINT_NAME, C.CONSTRAINT_TYPE, CC.COLUMN_NAME 
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE UPPER(C.TABLE_NAME)='DEPARTSEQ'
AND
C.CONSTRAINT_NAME=CC.CONSTRAINT_NAME;

SELECT * FROM DEPARTSEQ;

--2
/*Crea una secuencia para utilizarla con la columna de clave primaria de 
la tabla DEPARTSEQ. La secuencia debe comenzar en 200 y tener un valor 
máximo de 1000. Haz que la secuencia aumente en diez números cada vez. 
Asigna a la secuencia el nombre DEPT_ID_SEQ. Comprueba en el diccionario 
de datos que el objeto se ha creado correctamente.*/
DROP SEQUENCE DEPT_ID_SEQ;
CREATE SEQUENCE DEPT_ID_SEQ
START WITH 200
MAXVALUE 1000
INCREMENT BY 10
NOCYCLE
NOCACHE;

DESC USER_SEQUENCES

SELECT SEQUENCE_NAME
FROM USER_SEQUENCES;

--3
/*Consulta en el diccionario de datos acerca de tus secuencias.
Obtén la siguiente información: nombre de secuencia, valor máximo,
tamaño de aumento y último número. */
DESC USER_SEQUENCES;

SELECT SEQUENCE_NAME, MAX_VALUE, INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES;

--4
/*Escribe un archivo de comandos para insertar dos filas en la tabla
DEPARTASEQ. Asigna al archivo de comandos el nombre lab9_4.sql.
Asegúrate de utilizar la secuencia que creaste anteriormente para
la columna ID. Agrega dos departamentos llamados Educacion
y Administracion. Ejecuta el script. Confirma las inserciones. */

--ESTA EN lab9_4.sql

--5
/*Comprueba cual será el siguiente número de departamento, 
que dará la secuencia que has creado, al realizar la siguiente inserción.*/
SELECT DEPT_ID_SEQ.NEXTVAL
FROM DUAL;
/*AÑADIR UN NUEVO DEPARTAMENTO CON LA SEQUENCIA RECIEN CREADA*/
INSERT INTO DEPARTSEQ VALUES 
(DEPT_ID_SEQ.CURRVAL, 'MOLANO', 'MIRANDA');

SELECT * FROM DEPARTSEQ
WHERE UPPER(DNOMBRE)='MOLANO';

--ROLLBACK Y COMPROBACION
ROLLBACK;
SELECT * FROM DEPARTSEQ;

--6
/*Crear la tabla CENTROS teniendo en cuenta este modelo y 
que el modelo físico se va a implementar en 
un SGBD Oracle 12c:*/
DROP TABLE CENTROS;

CREATE TABLE CENTROS (
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY 
            MINVALUE 1 
            MAXVALUE 99 
            INCREMENT BY 1 
            START WITH 1 
            NOCYCLE 
            NOCACHE,
NOMBRE VARCHAR2(30) NOT NULL,
CALLE VARCHAR2(30),
NUMERO NUMBER(2),
CP VARCHAR2(5),
CIUDAD VARCHAR2(15),
PROVINCIA VARCHAR2(40),
TELEFONO VARCHAR2(9),
CONSTRAINT CENTROS_ID_PK PRIMARY KEY (ID)
);
--PASOS PARA LA COMPROBACION DE TABLA
--1.COMPROBAR QUE ESTA EN EL DICCIONARIO
DESC USER_TABLES;

SELECT TABLE_NAME
FROM USER_TABLES
WHERE UPPER(TABLE_NAME)='CENTROS';

--2.COMPROBAR LAS COLUMNAS DE LA TABLA
DESC CENTROS;

--PASO PARA COMPROBAR LA RESTRICCIONES
DESC USER_CONSTRAINTS;
DESC USER_CONS_COLUMNS;

SELECT C.CONSTRAINT_NAME, 
C.CONSTRAINT_TYPE, C.TABLE_NAME, CC.COLUMN_NAME,
C.GENERATED
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE C.CONSTRAINT_NAME=CC.CONSTRAINT_NAME --JOIN
AND
UPPER(C.TABLE_NAME)='CENTROS';

--SACAR EL NOMBRE DE LA SEQUENCIA DE ID('ISEQ$$_328325')
SELECT TABLE_NAME, COLUMN_NAME, DATA_DEFAULT FROM USER_TAB_COLUMNS
WHERE TABLE_NAME='CENTROS';

SELECT LAST_NUMBER, INCREMENT_BY,MIN_VALUE, MAX_VALUE
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='ISEQ$$_328325';

--7
/*Realiza la inserción de un centro. Inventa los datos.*/
INSERT INTO CENTROS (NOMBRE,CALLE,NUMERO,CP,CIUDAD,PROVINCIA,TELEFONO)
VALUES('ARRIAGA','PORTAL DE CASTILLA',13,01008,'VITORIA','ALAVA','123456789');

SELECT * FROM CENTROS;

--8
/*Crear un índice no único en la columna de claves ajenas 
(DEPT_NO) en la tabla EMPLE.*/
DROP INDEX IND_EMP_DEPT;

CREATE INDEX IND_EMP_DEPT
ON EMPLE(DEPT_NO);

--9

DESC USER_INDEXES;

SELECT INDEX_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE TABLE_NAME='EMPLE';

--10
DROP INDEX IND_EMP_DEPT;

--11
CREATE INDEX IND_DEPT_NOMBRE
ON DEPART(UPPER(DNOMBRE));

--13
ALTER INDEX IND_DEPT_NOMBRE MONITORING USAGE;

SELECT *
FROM V$OBJECT_USAGE;

--COMPROBAR LA MONITORIZACON PARA VER SI ORACLE 
--UTILIZA EL INDEX CREADO ANTERIORMENTE

--14
SELECT MONITORING
FROM USER_INDEXES;

SELECT *
FROM DEPART;
--COMPROBACION DEL INDICE
SELECT *
FROM V$OBJECT_USAGE;


SELECT *
FROM DEPART
WHERE UPPER(DNOMBRE) LIKE '%A%';
--COMPROBACION DEL INDICE
SELECT *
FROM V$OBJECT_USAGE;

--DESACTIVACION DE LA MONITORIZACION
ALTER INDEX IND_DEPT_NOMBRE NOMONITORING USAGE;

--15
DROP SYNONYM DEP;

CREATE SYNONYM DEP
FOR DEPARTAMENTOS;

RENAME DEPART TO DEPARTAMENTOS;

SELECT TABLE_NAME
FROM USER_TABLES;

SELECT *
FROM DEP;







--EJERCICIOS DE REPASO
/*OBTENER APELLIDO Y OFICIO DE LOS EMPLEADOS QUE TIENEN EL MISMO
OFICIO Y EL MISMO DEPARTAMENTO QUE EL DEPARTAMENTO DE INVESTIGACION*/

SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE OFICIO IN(SELECT DISTINCT OFICIO
                FROM EMPLE
                WHERE DEPT_NO=(SELECT DEPT_NO
                                FROM DEPARTAMENTOS
                                WHERE UPPER(DNOMBRE)='INVESTIGACION'));
    
/*VISUALIZAR EL NUMERO DE DEPARTAMENTO EL OFICIO Y EL SALARIO
DE LOS EMPLEADOS DE LOS  OFICIOS CON MAYOR SALARIO DE CADA DEPARTAMETO*/
SELECT DEPT_NO, OFICIO, SALARIO, APELLIDO
FROM EMPLE 
WHERE SALARIO IN(SELECT MAX(SALARIO)
                FROM EMPLE
                GROUP BY DEPT_NO);
    
SELECT E.DEPT_NO, E.OFICIO, E.SALARIO, E.APELLIDO
FROM EMPLE E
WHERE E.SALARIO IN(SELECT MAX(EM.SALARIO)
                FROM EMPLE EM
                WHERE EM.DEPT_NO=E.DEPT_NO
                GROUP BY DEPT_NO);

/*ELIMINAR LOS DEPARTAMENTOS QUE TIENEN MENOS DE 2 EMPLEADOS*/
DELETE FROM DEP
WHERE DEPT_NO IN (SELECT DEPT_NO
                FROM EMPLE
                GROUP BY DEPT_NO
                HAVING COUNT(*)>=2);

ROLLBACK;

/*AUMENTAR 5000 A AQUELLOS QUE NO TENGAN EL DEPARTAMENTO EN MADRID*/
SELECT EMP_NO, SALARIO
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO
                    FROM DEP
                    WHERE UPPER(LOC)!='MADRID');

UPDATE EMPLE 
SET SALARIO=SALARIO+5000
WHERE DEPT_NO IN(SELECT DEPT_NO
                FROM DEP
                WHERE UPPER(LOC)!='MADRID')









